### ISSUE TITLE
Compilation errors on windows

### ISSUE THREAD

**Issue by iAndyHD3** [WerWolv/Fenestra#3]
1. When running `cmake -B build` freetype wasn't found and I needed to include it using fetch content
2. After including freetype through cmake and running `cmake --build build`, A few undefined reference errors:
```
build/_deps/fenestra-src/lib/external/libwolv/libs/io/source/io/file_win.cpp:204:13: error: use of undeclared identifier 'wstat'
  204 |         if (wstat(this->m_path.c_str(), &fileInfo) != 0)
      |             ^
/build/_deps/fenestra-src/lib/external/libwolv/libs/io/source/io/file_win.cpp:214:31: error: use of undeclared identifier '_open_osfhandle'
  214 |         auto fileDescriptor = _open_osfhandle(intptr_t(m_handle), m_mode == Mode::Read ? _O_RDONLY : _O_WRONLY);
```
Missing include for _open_osfhandle, "io.h" was missing. On the other hand, `wstat` doesn't exist at all, but `_wstat` does. 
3. After changing the code to make this compile I get several more errors:
Missing include `<ft2build.h>` in `imgui_freetype.cpp`, and a few more undefined reference errors in opengl headers.

I'm using ninja + clang on windows and I used the template to generate the project. I also tried generating a vs2022 solution and I got different errors. Has windows ever been tested?

**Comment by WerWolv** [comment]
Hey, Windows only works when using the MinGW environment, MSVC and other VS-related stuff is not supported right now.

**Comment by iAndyHD3** [comment]
That makes sense, consider adding a note in the readme in that case.

**Comment by iAndyHD3** [comment]
Successfully compiled with mingw environment so I will close this issue. As a sidenote, I'm experiencing [this resizing issue](https://github.com/WerWolv/ImHex/issues/1842) both in the Fenestra template and in ImHex. It seems to be AMD specific.
